import type { Course } from "@/types/learning"

export const courses: Course[] = [
  {
    id: "1",
    number: 1,
    title: "Foundations of NICU Pumping Care",
    goal: "Understand why early pumping matters and how to introduce the pathway safely.",
    duration: "30 min",
    modules: [
      { title: "Role of milk for NICU infants", links: [{ label: "Providing Milk for Your NICU Baby. Getting Started", href: "#", type: "pdf" }] },
      { title: "Why pump type matters in NICU", links: [{ label: "Does the Type of Breast Pump Matter for a NICU Mom?", href: "#", type: "pdf" }] },
      { title: "First 14 days and mammary gland programming", links: [{ label: "Coming to Volume", href: "#", type: "pdf" }] },
      { title: "Normal milk volume expectations", links: [{ label: "What is a Normal Amount of Milk to Pump?", href: "#", type: "pdf" }] },
    ],
    outcome: "Nurse understands physiology + sets realistic expectations.",
  },
  {
    id: "2",
    number: 2,
    title: "First Pumping Session (Golden 6 Hours)",
    goal: "Safely guide the mother through her first pumping experience.",
    modules: [
      { title: "First pump assisted checklist" },
      { title: "Helping mother pump within 6 hours" },
      { title: "Sensations during pumping", links: [{ label: "What Will I Feel When I Use the Breast Pump?", href: "#", type: "pdf" }] },
      { title: "Emotional support & information overload avoidance" },
      { title: "Logging first pumping data" },
    ],
    outcome: "Nurse confidently supports first pumping without overwhelming mother.",
    duration: "45 min",
  },
  {
    id: "3",
    number: 3,
    title: "Pump Setup & Technical Training",
    goal: "Make nurses experts in pump operation and teaching.",
    modules: [
      { title: "Symphony pump overview", links: [{ label: "Symphony overview sheet", href: "#", type: "sheet" }] },
      { title: "Pump assembly", links: [{ label: "Assemble pump", href: "https://www.youtube.com/watch?v=4mdW147w7AM", type: "video" }] },
      { title: "Initiation program", links: [{ label: "Start initiate program", href: "https://www.youtube.com/watch?v=3Nhqj_YXjs4", type: "video" }] },
      { title: "Which program to use when", links: [{ label: "Program selection", href: "https://www.youtube.com/watch?v=rI5Y7TqQFTo", type: "video" }] },
    ],
    outcome: "Nurse can train mothers independently.",
    duration: "25 min",
  },
  {
    id: "4",
    number: 4,
    title: "Breast & Nipple Assessment",
    goal: "Clinical assessment before pumping begins.",
    modules: [
      { title: "Evaluating nipple base", links: [{ label: "Education sheet", href: "#", type: "sheet" }] },
      { title: "Evaluating nipple circumference", links: [{ label: "Education sheet", href: "#", type: "sheet" }] },
      { title: "Evaluating nipple elasticity", links: [{ label: "Education sheet", href: "#", type: "sheet" }] },
      { title: "Identifying early complications" },
      { title: "Reporting issues via NICU app" },
    ],
    outcome: "Early prevention of injury and lactation failure.",
    duration: "35 min",
  },
  {
    id: "5",
    number: 5,
    title: "Breast Shield Personalization",
    goal: "Proper fitting to prevent pain and increase milk output.",
    modules: [
      { title: "Choosing breast shield size", links: [{ label: "Considerations when Choosing a Breast Shield", href: "#", type: "pdf" }] },
      { title: "Correct fit principles", links: [{ label: "Getting the Right Fit: Breast Shields", href: "#", type: "pdf" }] },
      { title: "When shield is too large", links: [{ label: "Assessment & Adjustment", href: "#", type: "pdf" }] },
      { title: "Areolar movement rules (≤ 1/8 inch)" },
      { title: "Size changes during first 14 days" },
    ],
    outcome: "Nurse personalizes pumping setup safely.",
    duration: "40 min",
  },
  {
    id: "6",
    number: 6,
    title: "Assisted Pumping Optimization",
    goal: "Improve efficiency and comfort during sessions.",
    modules: [
      { title: "Double pumping benefits" },
      { title: "What to watch during pumping", links: [{ label: "Watch While Pumping (PDF)", href: "https://strapi-lactahub.org/uploads/17_watchwhilepumping_final_july_6_3f3fb32f1c.pdf", type: "pdf" }] },
      { title: "Nipple centering", links: [{ label: "Centering nipple video", href: "#", type: "video" }] },
      { title: "Off-center correction", links: [{ label: "Adjustment video", href: "#", type: "video" }] },
      { title: "Optimal breast shield pressure", links: [{ label: "Pressure video", href: "#", type: "video" }] },
    ],
    outcome: "Nurses can troubleshoot live pumping problems.",
    duration: "20 min",
  },
  {
    id: "7",
    number: 7,
    title: "Vacuum Pressure & Milk Removal Optimization",
    goal: "Teach personalization for comfort + milk production.",
    modules: [
      { title: "Finding maximum comfortable vacuum", links: [{ label: "Optimizing Milk Removal", href: "https://lactahub.org/category-4-pumping-nicu-infant/#ref13", type: "video" }] },
      { title: "Signs of too much pressure" },
      { title: "Signs of insufficient pressure" },
      { title: "Daily reassessment teaching" },
    ],
    outcome: "Higher milk output with reduced injury risk.",
    duration: "30 min",
  },
  {
    id: "8",
    number: 8,
    title: "Building the Personalized Pumping Plan",
    goal: "Transition from session support to long-term success.",
    modules: [
      { title: "Pump frequency targets (5–8/day)" },
      { title: "Volume milestones (≥20 mL)" },
      { title: "Transition initiation → maintenance" },
      { title: "Red flag monitoring" },
      { title: "Normal physiological responses" },
    ],
    outcome: "Mother leaves with a structured, achievable plan.",
    duration: "25 min",
  },
  {
    id: "9",
    number: 9,
    title: "Digital Support & NICU App Workflow",
    goal: "Integrate clinical care with digital monitoring.",
    modules: [
      { title: "Activating NICU Mom App" },
      { title: "Logging pumping sessions" },
      { title: "Reporting symptoms" },
      { title: "Creating alerts" },
      { title: "Preparing for PP1 consultation" },
    ],
    outcome: "Nurses use digital tools consistently.",
    duration: "15 min",
  },
  {
    id: "10",
    number: 10,
    title: "Follow-Up & Consultation Preparation",
    goal: "Structured ongoing care.",
    modules: [
      { title: "Preparing for first consultation" },
      { title: "Reviewing pumping data trends" },
      { title: "Milk volume progression coaching" },
      { title: "Preparing PP2 consultation" },
    ],
    outcome: "Standardized follow-up across NICU staff.",
    duration: "20 min",
  },
]
